name: FF merge
on:
  pull_request:
    types:
      - labeled

jobs:
  merge-upstream:
    runs-on: ubuntu-20.04
    if: github.event.label.name == 'ff-merge'

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          submodules: true

      - name: FF merge
        shell: bash
        run: |
          # https://github.com/robotology/gh-action-nightly-merge/pull/13
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          git remote add target "https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY.git"

          git fetch origin ${{ github.event.pull_request.head.sha }}
          git merge --ff-only ${{ github.event.pull_request.head.sha }}
          git push target main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
